version: '3.3'

services:
    server:
        build: server/
        command: ./start.sh
        cap_add:
            - NET_ADMIN
        networks:
            my-net:
                ipv4_address: 173.20.0.2

    client1:
        build:
            dockerfile: Dockerfile
            context: client
            args:
                - NUM=1
        command: sleep infinity
        networks:
            my-net:
                ipv4_address: 173.20.1.0
        depends_on:
            - server

    client2:
        build:
            dockerfile: Dockerfile
            context: client
            args:
                - NUM=2
        command: sleep infinity
        networks:
            my-net:
                ipv4_address: 173.20.2.0
        depends_on:
            - server

    client3:
        build:
            dockerfile: Dockerfile
            context: client
            args:
                - NUM=3
        command: sleep infinity
        networks:
            my-net:
                ipv4_address: 173.20.3.0
        depends_on:
            - server

    client4:
        build:
            dockerfile: Dockerfile
            context: client
            args:
                - NUM=4
        command: sleep infinity
        networks:
            my-net:
                ipv4_address: 173.20.4.0
        depends_on:
            - server

networks:
    my-net:
        driver: bridge
        ipam:
            config:
                - subnet: 173.20.0.0/16